### ISSUE TITLE
Freecam + AFK = Move(AAC)

### ISSUE THREAD

**Issue by Terrifical** [Photon-GitHub/AACAdditionPro#118]
Players are getting glitched/kicked for "MoveTimer" They only get kicked when I'm using the optimized config BUT the glitch still happens with or without it. If I'm **standing still** my screen glitches and the map becomes invisible. If I'm using the optimized config the same thing would happen but I would just get kicked if I'm standing there for longer than one minute. I **think** AAC kicks me BUT it only happens when I have AACAddition in my plugins folder. (If that makes any sense).

When I'm using optimized config it kicks me for "MoveTimer". If I'm using the default config no notifications pop up, only the glitch occurs.
 

Video: https://www.youtube.com/watch?v=QPs1-clD3mA

Core information

Server version: 1.11.2

AAC version: 3.2.2-b1

AACAdditionPro version: 3.0.2-b2

ProtocolLib version: 4.3.0

Plugin list: http://prntscr.com/g3jsvv

Special environment information

ViaVersion version: N/A

ProtocolSupport version: 4.26

ViaBackwards version: N/A

BungeeCord plugins: N/A

**Comment by CeIebrimbor** [comment]
@Photon-GitHub 
Freecam causes this. Afk players will start sending too many packets as a result of Freecam and (eventually) get to kick levels. It only happens quicker because my Conditions kick faster under good-great conditions.

@Terrifical 
Disable Freecam and report back to see if it still happens. Also, do you have AACaddition 3.0.2-b3?

**Comment by Terrifical** [comment]
Alright, I disabled free-cam and the bug is no longer happening.

Yes. Just installed it the bug still happens when free-cam is enabled. If that was where you were going with that.

**Comment by CeIebrimbor** [comment]
> Alright, I disabled free-cam and the bug is no longer happening.
> 
> Yes. Just installed it the bug still happens when free-cam is enabled. If that was where you were going with that.

Yes. Thank you for confirming. Now it's up to Photon. Luckily, the Freecam check is not ciritcal on most servers. Hopefully, yours is not an exception since move cannot be disabled. You only other alternative is to disable kicking on Move and just let AFK players violation go off into the sunset forever.

**Comment by CeIebrimbor** [comment]
Now being lumped together with being sucked into blocks with the AAC bug.

Exploit: https://github.com/konsolas/AAC-Issues/issues/914

**Comment by CeIebrimbor** [comment]
@Photon-GitHub 
Fixed with AAC 3.3.4 (possibly)?

**Comment by Janmm14** [comment]
@Terrifical Recheck with AAC 3.3.4 please.

**Comment by Photon-GitHub** [comment]
^^

**Comment by Photon-GitHub** [comment]
Apparently inactive and fixed in AAC itself. Please reopen if it occurs again.
