### ISSUE TITLE
KillauraEntity FP

### ISSUE THREAD

**Issue by Hyronymos** [Photon-GitHub/AACAdditionPro#125]
Latest AAC & AACAdditionPro

Server-Log: https://pastebin.com/3Q6wBB9h
AACAdditionPro-Log: https://pastebin.com/ueKqN7YB
Video: https://youtu.be/45uGHjsSsTY

**Comment by CeIebrimbor** [comment]
Looks like flawless ping.

**Comment by ItzSomebody** [comment]
Who on earth is going to spend a minute and a half hitting the killaura entity?

**Comment by Hyronymos** [comment]
Twerion Staff Members xD

**Comment by CeIebrimbor** [comment]
That has always been an issue with spawned entities... Players hit it knowing what happens after they do, then cry wolf to the owner.

**Comment by Photon-GitHub** [comment]
I will slightly increase the vl-decay rate to solve this problem.

**Comment by Photon-GitHub** [comment]
Should be more balanced in the new version. And if your staff now hits this entity for 3 minutes in order to get intentionally punished I will not decrease the detection speed of the speed again as this is clearly an unusual playstyle :smiley:

**Comment by Hyronymos** [comment]
Not fixed, still broken.

**Comment by Photon-GitHub** [comment]
Read my last post. I am not going to address this issue if your staff team thinks that trying to hit the entity for several minutes in order to get kicked it is a great idea. If you your staff team cannot live with that kind of common sense and normal playstyle please deactivate the check or increase the thresholds.

**Comment by Hyronymos** [comment]
You should look into AACAdditionpro discord
