### ISSUE TITLE
authme

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#259]
Please include:
- Server version: 1.12.2
- ProtocolLib version: 4.4.0
- The version of AACAdditionPro: 4.0.3 
- A detailed description of the bug / wanted feature: 
when people join on prehub with aac and aacpro, aacpro can't see liteloader mod cause authme send player to other server after /login or /register
- If possible a short video of the bug:

**Comment by leoncp9** [comment]
i have auto login for some times

**Comment by Photon-GitHub** [comment]
Can you elaborate what happens exactly? Liteloader is not detected on a server that happens to handle your registration and uses AACAdditionPro?

**Comment by leoncp9** [comment]
yes liteloader  is not detected  because authme send player on hub fast

**Comment by leoncp9** [comment]
you can try to use liteloader on this server 163.172.109.78:25643, you can bypass the control on prehub, but not on  hub , i have  AACAdditionPro on prehub and hub for kick liteloader (i don't knwo how... but one user show me one client 1.8 who can download my map and bypass  AACAdditionPro control)

**Comment by Janmm14** [comment]
@leoncp9 The map download blockage is just working because the popular mods built in possibilities for such a blockage. Blocking all map download mods is impossible, some people got the idea to use tricks like configuring orebfuscator in mode 2 and put in some ores, but also tnt and redstone blocks so the downloaded map explodes when loaded.

**Comment by leoncp9** [comment]
i don't understand. but okay
