### ISSUE TITLE
Inventory false positives

### ISSUE THREAD

**Issue by BestMark** [Photon-GitHub/AACAdditionPro#329]
Hello,
Inventory check still kicks players.
Video: https://www.youtube.com/watch?time_continue=1&v=fG5z9Su8HHQ
Log: https://pastebin.com/6dAZEMqq

**Comment by Photon-GitHub** [comment]
Given the information you wrote me on discord, this is not at all a problem of AACAdditionPro. You use ProtocolSupport which is explicitly listed as incompatible to AAC, the opened inventory is done by an unnamed plugin and I don’t know what happened there but I assume that the inventory was not closed correctly, which again might be caused by a bad programming of the shop plugin, protocolsupport or by the client which is in no way vanilla.

Please report again if you can reproduce this with a vanilla client on a non-ProtocolSupport server and have verified that the shop plugin works correctly.

**Comment by BestMark** [comment]
It was same problem when I used ViaVersion on 1.12.2 and the other minigame with different shop

**Comment by BestMark** [comment]
https://github.com/Photon-GitHub/AACAdditionPro/issues/293
